// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <RcppArmadillo.h>
#include <Rcpp.h>

using namespace Rcpp;

// good
void good(double a);
RcppExport SEXP _DDPGPSurv_good(SEXP aSEXP) {
BEGIN_RCPP
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< double >::type a(aSEXP);
    good(a);
    return R_NilValue;
END_RCPP
}
// showD
void showD(double b, double a);
RcppExport SEXP _DDPGPSurv_showD(SEXP bSEXP, SEXP aSEXP) {
BEGIN_RCPP
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< double >::type b(bSEXP);
    Rcpp::traits::input_parameter< double >::type a(aSEXP);
    showD(b, a);
    return R_NilValue;
END_RCPP
}
// showRowvec
void showRowvec(arma::rowvec b);
RcppExport SEXP _DDPGPSurv_showRowvec(SEXP bSEXP) {
BEGIN_RCPP
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< arma::rowvec >::type b(bSEXP);
    showRowvec(b);
    return R_NilValue;
END_RCPP
}
// showMatrix
void showMatrix(arma::mat b);
RcppExport SEXP _DDPGPSurv_showMatrix(SEXP bSEXP) {
BEGIN_RCPP
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< arma::mat >::type b(bSEXP);
    showMatrix(b);
    return R_NilValue;
END_RCPP
}
// stab
void stab(arma::rowvec b);
RcppExport SEXP _DDPGPSurv_stab(SEXP bSEXP) {
BEGIN_RCPP
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< arma::rowvec >::type b(bSEXP);
    stab(b);
    return R_NilValue;
END_RCPP
}
// update_r_within_testing
List update_r_within_testing(double sigma2, int Npat, arma::rowvec censor_status, arma::rowvec response, arma::rowvec r, arma::mat covariance, arma::mat cov, int H, double M, arma::rowvec ns, arma::rowvec impute_y, arma::mat muh_temp, arma::rowvec beta_0, int Ncov, Function samp, Function rtrunc, Function rmvn, arma::mat A_inv, arma::mat A);
RcppExport SEXP _DDPGPSurv_update_r_within_testing(SEXP sigma2SEXP, SEXP NpatSEXP, SEXP censor_statusSEXP, SEXP responseSEXP, SEXP rSEXP, SEXP covarianceSEXP, SEXP covSEXP, SEXP HSEXP, SEXP MSEXP, SEXP nsSEXP, SEXP impute_ySEXP, SEXP muh_tempSEXP, SEXP beta_0SEXP, SEXP NcovSEXP, SEXP sampSEXP, SEXP rtruncSEXP, SEXP rmvnSEXP, SEXP A_invSEXP, SEXP ASEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< double >::type sigma2(sigma2SEXP);
    Rcpp::traits::input_parameter< int >::type Npat(NpatSEXP);
    Rcpp::traits::input_parameter< arma::rowvec >::type censor_status(censor_statusSEXP);
    Rcpp::traits::input_parameter< arma::rowvec >::type response(responseSEXP);
    Rcpp::traits::input_parameter< arma::rowvec >::type r(rSEXP);
    Rcpp::traits::input_parameter< arma::mat >::type covariance(covarianceSEXP);
    Rcpp::traits::input_parameter< arma::mat >::type cov(covSEXP);
    Rcpp::traits::input_parameter< int >::type H(HSEXP);
    Rcpp::traits::input_parameter< double >::type M(MSEXP);
    Rcpp::traits::input_parameter< arma::rowvec >::type ns(nsSEXP);
    Rcpp::traits::input_parameter< arma::rowvec >::type impute_y(impute_ySEXP);
    Rcpp::traits::input_parameter< arma::mat >::type muh_temp(muh_tempSEXP);
    Rcpp::traits::input_parameter< arma::rowvec >::type beta_0(beta_0SEXP);
    Rcpp::traits::input_parameter< int >::type Ncov(NcovSEXP);
    Rcpp::traits::input_parameter< Function >::type samp(sampSEXP);
    Rcpp::traits::input_parameter< Function >::type rtrunc(rtruncSEXP);
    Rcpp::traits::input_parameter< Function >::type rmvn(rmvnSEXP);
    Rcpp::traits::input_parameter< arma::mat >::type A_inv(A_invSEXP);
    Rcpp::traits::input_parameter< arma::mat >::type A(ASEXP);
    rcpp_result_gen = Rcpp::wrap(update_r_within_testing(sigma2, Npat, censor_status, response, r, covariance, cov, H, M, ns, impute_y, muh_temp, beta_0, Ncov, samp, rtrunc, rmvn, A_inv, A));
    return rcpp_result_gen;
END_RCPP
}
// fmeansurviv
arma::rowvec fmeansurviv(arma::rowvec x, SEXP r, arma::mat cov, arma::rowvec pat_cov, int H, arma::mat betah, arma::mat inv_covariance, arma::mat muh, int Npat, double M, int Ncov, double sigma2, arma::rowvec beta_0);
RcppExport SEXP _DDPGPSurv_fmeansurviv(SEXP xSEXP, SEXP rSEXP, SEXP covSEXP, SEXP pat_covSEXP, SEXP HSEXP, SEXP betahSEXP, SEXP inv_covarianceSEXP, SEXP muhSEXP, SEXP NpatSEXP, SEXP MSEXP, SEXP NcovSEXP, SEXP sigma2SEXP, SEXP beta_0SEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< arma::rowvec >::type x(xSEXP);
    Rcpp::traits::input_parameter< SEXP >::type r(rSEXP);
    Rcpp::traits::input_parameter< arma::mat >::type cov(covSEXP);
    Rcpp::traits::input_parameter< arma::rowvec >::type pat_cov(pat_covSEXP);
    Rcpp::traits::input_parameter< int >::type H(HSEXP);
    Rcpp::traits::input_parameter< arma::mat >::type betah(betahSEXP);
    Rcpp::traits::input_parameter< arma::mat >::type inv_covariance(inv_covarianceSEXP);
    Rcpp::traits::input_parameter< arma::mat >::type muh(muhSEXP);
    Rcpp::traits::input_parameter< int >::type Npat(NpatSEXP);
    Rcpp::traits::input_parameter< double >::type M(MSEXP);
    Rcpp::traits::input_parameter< int >::type Ncov(NcovSEXP);
    Rcpp::traits::input_parameter< double >::type sigma2(sigma2SEXP);
    Rcpp::traits::input_parameter< arma::rowvec >::type beta_0(beta_0SEXP);
    rcpp_result_gen = Rcpp::wrap(fmeansurviv(x, r, cov, pat_cov, H, betah, inv_covariance, muh, Npat, M, Ncov, sigma2, beta_0));
    return rcpp_result_gen;
END_RCPP
}
// RcppTable
IntegerVector RcppTable(SEXP x);
RcppExport SEXP _DDPGPSurv_RcppTable(SEXP xSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< SEXP >::type x(xSEXP);
    rcpp_result_gen = Rcpp::wrap(RcppTable(x));
    return rcpp_result_gen;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_DDPGPSurv_good", (DL_FUNC) &_DDPGPSurv_good, 1},
    {"_DDPGPSurv_showD", (DL_FUNC) &_DDPGPSurv_showD, 2},
    {"_DDPGPSurv_showRowvec", (DL_FUNC) &_DDPGPSurv_showRowvec, 1},
    {"_DDPGPSurv_showMatrix", (DL_FUNC) &_DDPGPSurv_showMatrix, 1},
    {"_DDPGPSurv_stab", (DL_FUNC) &_DDPGPSurv_stab, 1},
    {"_DDPGPSurv_update_r_within_testing", (DL_FUNC) &_DDPGPSurv_update_r_within_testing, 19},
    {"_DDPGPSurv_fmeansurviv", (DL_FUNC) &_DDPGPSurv_fmeansurviv, 13},
    {"_DDPGPSurv_RcppTable", (DL_FUNC) &_DDPGPSurv_RcppTable, 1},
    {NULL, NULL, 0}
};

RcppExport void R_init_DDPGPSurv(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
