# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

good <- function(a) {
    invisible(.Call('_DDPGPSurv_good', PACKAGE = 'DDPGPSurv', a))
}

showD <- function(b, a) {
    invisible(.Call('_DDPGPSurv_showD', PACKAGE = 'DDPGPSurv', b, a))
}

showRowvec <- function(b) {
    invisible(.Call('_DDPGPSurv_showRowvec', PACKAGE = 'DDPGPSurv', b))
}

showMatrix <- function(b) {
    invisible(.Call('_DDPGPSurv_showMatrix', PACKAGE = 'DDPGPSurv', b))
}

stab <- function(b) {
    invisible(.Call('_DDPGPSurv_stab', PACKAGE = 'DDPGPSurv', b))
}

update_r_within_testing <- function(sigma2, Npat, censor_status, response, r, covariance, cov, H, M, ns, impute_y, muh_temp, beta_0, Ncov, samp, rtrunc, rmvn, A_inv, A) {
    .Call('_DDPGPSurv_update_r_within_testing', PACKAGE = 'DDPGPSurv', sigma2, Npat, censor_status, response, r, covariance, cov, H, M, ns, impute_y, muh_temp, beta_0, Ncov, samp, rtrunc, rmvn, A_inv, A)
}

fmeansurviv <- function(x, r, cov, pat_cov, H, betah, inv_covariance, muh, Npat, M, Ncov, sigma2, beta_0) {
    .Call('_DDPGPSurv_fmeansurviv', PACKAGE = 'DDPGPSurv', x, r, cov, pat_cov, H, betah, inv_covariance, muh, Npat, M, Ncov, sigma2, beta_0)
}

RcppTable <- function(x) {
    .Call('_DDPGPSurv_RcppTable', PACKAGE = 'DDPGPSurv', x)
}

